//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDermatologia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
        
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            this.HistoriaClinica = new HashSet<HistoriaClinica>();
            this.Reserva = new HashSet<Reserva>();
        }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Cédula")]
        [RegularExpression("[0-9]+", ErrorMessage = "Ingrese solo números")]
        [StringLength(10, MinimumLength = 10)]
        public string Cedula { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Nombre")]
        [RegularExpression("[A-Za-z]+", ErrorMessage = "Ingrese solo letras")]
        [StringLength(60, MinimumLength = 3)]
        public string Nombre { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Apellido")]
        [RegularExpression("[A-Za-z]+", ErrorMessage = "Ingrese solo letras")]
        [StringLength(60, MinimumLength = 3)]
        public string Apellido { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Teléfono")]
        [RegularExpression("[0-9]+", ErrorMessage = "Ingrese solo números")]
        [StringLength(10, MinimumLength = 7)]
        public string Telefono { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "E-Mail")]
        [EmailAddress(ErrorMessage = "Dirección E-Mail inválida")]
        public string Correo { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Dirección")]
        [StringLength(60,MinimumLength = 3)]
        public string Direccion { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Género")]
        [StringLength(1 , MinimumLength = 1, ErrorMessage = "Solo se admite un caractér M para masculino y F para femenino")]
        [RegularExpression("M|F", ErrorMessage = "Solo se admite un caractér M para masculino y F para femenino")]
        public string Sexo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoriaClinica> HistoriaClinica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }
    }
}
