//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppDermatologia.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Reserva
    {
        public int ID_Reserva { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Paciente")]
        public string IDPaciente { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        public Nullable<System.DateTime> Fecha { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Servicio")]
        public string Servicio { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Observaciones")]
        public string Observaciones { get; set; }
        [Required(ErrorMessage = "Campo Obligatorio")]
        [Display(Name = "Estado de Pago")]
        public string Estado { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
